name: the_assistant
description: A Flutter calendar application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.9
  cupertino_icons: ^1.0.2
  http: ^1.3.0
  record: ^4.4.4
  path_provider: ^2.0.15
  path: ^1.8.3
  google_fonts: ^6.1.0
  provider: ^6.1.1
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env 